"""posts feed and outbox

Revision ID: 5ab1114468de
Revises: 0ada3b627aa6
Create Date: 2026-09-30 17:30:24.041885
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "5ab1114468de"
down_revision = "0ada3b627aa6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.BigInteger(), nullable=False),
        sa.Column("followee_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("follower_id <> followee_id", name=op.f("ck_follows_different_users")),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["users.id"],
            name=op.f("fk_follows_followee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name=op.f("pk_follows")),
    )
    op.create_index(
        "ix_follows_followee_id", "follows", ["followee_id", "follower_id"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("image_key", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="created", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'published', 'deleted')", name=op.f("ck_posts_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_posts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    op.create_index(
        "ix_posts_user_created",
        "posts",
        ["user_id", sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "feed_entries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_feed_entries_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feed_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_entries")),
        sa.UniqueConstraint("user_id", "post_id", name=op.f("uq_feed_entries_user_id")),
    )
    op.create_index(
        "ix_feed_entries_user_created",
        "feed_entries",
        ["user_id", sa.literal_column("created_at DESC"), sa.literal_column("post_id DESC")],
        unique=False,
    )
    op.create_table(
        "posts_outbox",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "event_type IN ('CREATED POST', 'UPDATED POST', 'DELETED POST')",
            name=op.f("ck_posts_outbox_valid_event"),
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_posts_outbox_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts_outbox")),
    )
    op.create_index(
        "ix_posts_outbox_pending",
        "posts_outbox",
        ["id"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_posts_outbox_pending",
        table_name="posts_outbox",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_table("posts_outbox")
    op.drop_index("ix_feed_entries_user_created", table_name="feed_entries")
    op.drop_table("feed_entries")
    op.drop_index(
        "ix_posts_user_created", table_name="posts", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("posts")
    op.drop_index("ix_follows_followee_id", table_name="follows")
    op.drop_table("follows")
    # ### end Alembic commands ###
